version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-php
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
    networks:
      - lamp-network
    depends_on:
      - db


  db:
    image: mariadb:10.6.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tecweb
      MYSQL_DATABASE: tecweb
      MYSQL_USER: tecweb
      MYSQL_PASSWORD: tecweb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Mirko2024
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lamp-network

volumes:
  db_data:

networks:
  lamp-network:
